# Generated by Django 3.0.3 on 2020-02-04 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('wishlist_link', models.TextField(blank=True, null=True)),
                ('requesting_shelter', models.IntegerField()),
                ('approved', models.BooleanField(default=False)),
                ('ordered', models.BooleanField(default=False)),
                ('delivered', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('poc', models.TextField(blank=True, null=True)),
                ('username', models.CharField(max_length=50)),
            ],
        ),
    ]
