# Generated by Django 2.2.5 on 2020-02-06 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ready', models.BooleanField()),
                ('occupied', models.BooleanField()),
                ('address', models.TextField()),
                ('bedrooms', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HousingRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bedrooms', models.IntegerField()),
                ('stay_duration', models.IntegerField()),
                ('moved_in', models.BooleanField()),
                ('checked_out', models.BooleanField()),
            ],
        ),
    ]
